### ISSUE TITLE
Create Project Plan

### ISSUE THREAD

**Issue by ngdhuy** [ngdhuy/se-capstone-project#1]
Get information of Project and Create Project plan Document

1. Kick-off meeting with client. 
2. Get draft requirement. 
3. Creat Project Plan document

**Comment by ngdhuy** [comment]
Kick-off meeting with client  - Meeting note

> Requirement
>> 1. Build a online e-commerce for selling toys and teddy-bear for children.
>> 2. The system support payment online for Vietnamese Market.
>> 3. The client can monitor real-time sales statistics and get report for sales.

> Time-line for project is 1 month

> Technical request is NONE

**Comment by ngdhuy** [comment]
@ngdhuy  Create Project Plan

- [x] Search and Create template for Project Plan
- [x] Create Project Plan Document with project information
- [x] Present with team and Public

**Comment by ngdhuy** [comment]
Using document template from https://sceweb.sce.uhcl.edu/helm/RUP_Folder/RationalUnifiedProcess/process/templates.htm
